const allLang = ['en', 'cz', 'ru', ]
if (localStorage.getItem('language')) {
    $('#main-language').html(localStorage.getItem('language'))
}

function changeURLLanguage(language) {
    localStorage.setItem('language', language)
    location.href = window.location.pathname + '#' + language;
    location.reload();
}
document.addEventListener('DOMContentLoaded', getLocalLang)
var arrLang = {
    'cz': {
        'about': 'O nás',
        'services': 'Služby',
        'contact': 'Kontakty',
        'reserve': 'Rezervovat',
        'about1': 'Mezinárodní tým specialistů na Vaši krásu Podium | Wella Salon poskytuje kompletní nabídku služeb, které souvisí s módním průmyslem a vnějším zdravím. Profesionalismus expertů Podium|Wella Salon našemu týmu umožňuje dynamický rozvoj v této oblasti a sledování nových technologií a produktů průmyslu. V Podium | Wella Salon máme několik směrů, proto je koncepce salonu založena na možnosti rozdělení na speciální zóny vybavené nejnovějšími technologiemi. Tato možnost našim specialistům vytváří podmínky pro úplné ponoření se do práce s klientem, což zajišťuje také komfortní podmínky pro komunikaci. Kadeřnická zóna je místo, kde se rodí móda. Analyzujeme zde Váš vzhled, měníme image a zdůrazňujeme Vaši přírodní krásu. U nás se budete cítit uvolněně a příjemně. Nebudeme Vám vnucovat poslední trendy, jelikož hlavní úspěch specialisty spočívá v tom, aby klient odešel šťastný a spokojený se svým novým vzhledem.',
        'about2': 'Kadeřnická zóna je místo, kde se rodí móda. Analyzujeme zde Váš vzhled, měníme image a zdůrazňujeme Vaši přírodní krásu. U nás se budete cítit uvolněně a příjemně. Nebudeme Vám vnucovat poslední trendy, jelikož hlavní úspěch specialisty spočívá v tom, aby klient odešel šťastný a spokojený se svým novým vzhledem.',
        'about3': 'Zóna vizážistů je naplněna novými styly a slovo dokonalost tady získává nový rozměr. Ve světě reflektorů a blesků fotoaparátů budete bezchybní. Není vůbec důležité, jaké máte na večer plány. Možná zůstanete skromní a zvolíte jemné „nude“ líčení nebo Vás čekají ambiciózní plány sexuálního a vášnivého vzhledu a sáhnete po kouřovém líčení. Make-up v každém případě vydrží na Vašem obličeji až do samotného rána.',
        'about4': 'Technické vybavení zóny estetické medicíny nedovolí provedení špatných procedur z minulého století, ale naopak ochrání zdraví a bezpečnost Vaší kůže, jelikož budou využity moderní technologie. Díky nám se zbavíte nahromaděného stresu ve Vašem obličeji, zastavíme čas a věnujeme Vám dodatečné hodiny relaxace a klidu ve Vašem životě.',
        'about5': 'V zóně určené pro manikúru se kreativní výtvory a ideální nehty již dávno staly realitou a součástí našeho života. V nejkrásnější části salonu PODIUM Vás čeká opravdový umělec a Vaše ruce budou jeho plátnem.',
        'offerText': 'Naše služby',
        'butn1': 'Сeník',
        'color': 'Kadeřnická zóna',
        'manicure': 'Zóna «G» Nail bar',
        'makeup': 'Zóna vizážistů',
        'cosmetics': 'Zóna Estetické Medicíny',
        'quote': 'Platíte jen tehdy, pokud jste spokojeni s našimi službami!',
        'follow': 'Sledujte nás na Instagramu',
        'nailbar': 'Zóna «G» Nail bar',
        'nailabout': 'Jemnost a přesnost jsou hlavními principy naší práce. Se zvláštní pozorností přistupujeme ke vzhledu Vašich rukou a děláme maximum pro Vaše pohodlí. Nehtový design je nejoblíbenějším procesem dané práce. I v tomto případě se řídíme individuálním přístupem, protože každý je jiný a preference v podobě manikúry jsou pro každého individuální. Neexistují pro nás hranice, protože i ty nejsmělejší nápady budou odraženy ve výsledné manikúře. Rádi splníme všechna Vaše přání.',
        'nail': 'Pánská manikúra',
        'nail1': 'Manikúra bez lakování',
        'nail2': 'Manikúra s lakováním',
        'nail3': 'Francouzská manikúra',
        'nail4': 'Manikúra + posílení nehtů',
        'nail5': 'Manikúra + úprava gelových nehtů',
        'nail6': 'Manikúra + gelové nehty',
        'min': '30 min',
        'min1': '40 min',
        'min2': '90 min',
        'min3': '90 min',
        'min4': '90 min',
        'min5': '90 min',
        'min6': '120 min',
        'visage': 'Služby zóny vizážistů',
        'visageabout': 'Make-up je způsob života a vědomá volba ženy, stejná jako volba stylu oblečení na každý den. Právě proto se dnes make-up stal směrem, jedním z typů současného moderního umění. Zdůrazní přírodní krásu, navíc zcela dokáže změnit obvyklý vzhled. Rafinovaný a rezervovaný make-up v jemných odstínech, odvážné kouřové líčení s třpytkami nebo klasika - výrazné rty a linky? Rádi s Vámi probereme a následně realizujeme jakékoliv, i ty nejodvážnější nápady. V zóně vizážistů také můžete využít služeb vytvoření ideálního tvaru obočí, protože pečlivé a dobře upravené obočí je jednou z částí bezchybného vzhledu.',
        'brow': 'Laminace obočí + úprava obočí',
        'brow1': 'Barvení barvou nebo hennou + úprava obočí',
        'brow2': 'Laminace + barvení + úprava obočí',
        'brow3': 'Denní make-up',
        'brow4': 'Večerní make-up',
        'brow5': 'Svatební make-up',
        'browtime': '40 min',
        'browtime1': '40 min',
        'browtime2': '60 min',
        'browtime3': '40 min',
        'browtime4': '60 min',
        'browtime5': '90 min',
        'browtext': 'Laminování chloupků speciálními směsmi značky THUYA PROFESSIONAL. Laminace dělá chloupky „poddajnější“ a vizuálně jim přidává na objemu. Účinek této dlouhodobé úpravy vydrží čtyři až šest týdnů. Úprava obočí je tvarování do požadovaného tvaru pomocí vosku ITALWAX a pinzety pro detailnější úpravu.',
        'browtext1': 'Při barvení používáme barvu značky THUYA PROFESSIONAL k získání maximálně přírodní barvy obočí a lehkého tónu na kůži. Díky keratinu a arganovému oleji je dobře vyživuje a pečuje o chloupky. K barvení hennou je využíván produkt populární značky BROWXENNA. Tento způsob barvení je vhodný pro milovníky jasných kontur a grafického obočí. Úprava obočí je tvarování do požadovaného tvaru pomocí vosku ITALWAX a pinzety pro detailnější úpravu.',
        'browtext2': 'Služba zahrnuje laminování chloupků speciálními směsmi značky THUYA PROFESSIONAL, barvení obočí barvou THUYA PROFESSIONAL nebo hennou BROWXENNA, úprava obočí je tvarování do požadovaného tvaru pomocí vosku ITALWAX a pinzety pro detailnější úpravu.',
        'browtext3': 'Každodenní vzhled je představen nenápadnými tóny, které zdůrazňují vaši přirozenost a zakrývají nedostatky, čímž Vám dodávají atraktivní a dobře upravený vzhled.',
        'browtext4': 'Jedná se o výraznější make-up, nejčastěji zvolený na večírek nebo slavnostní akci. Váš vzhled může být odvážný, nebo naopak něžný. Naši vizážisté vyberou kosmetiku s přihlédnutím ke všem vlastnostem vaší pokožky, aby byl Váš make-up po celý večer ideální.',
        'browtext5': 'Rádi vám pomůžeme vytvořit dokonalý svatební make-up, protože tento den by měl být nezapomenutelný, a Vy nejkrásnější. Svatební make-up musí zůstat bezchybný po celý den, ráno zdůrazňovat svěžest tváře a večer dodávat pokožce nádhernou záři.',
        'cosmetic': 'Zóna Estetické Medicíny',
        'kosmetika': 'Kosmetika',
        'kosmetika1': 'Laserová epilace',
        'kosmetika2': 'Diamantová mikrodermabraze',
        'kosmetika3': 'Fotorejuvenace',
        'kosmetika4': 'LPG lipomasáž',
        'kosmetika5': 'LPG lift masáž obličeje',
        'sluzba': 'Čištěni pleti ultrazvukem',
        'sluzba1': 'Vyživující čištěni pro problematickou pleť',
        'sluzba2': 'Profesionální chemické peelingy',
        'sluzba3': 'Regenerační ošetření',
        'sluzba4': 'Hydratační ošetření s vysokou koncentrací kyseliny hyaluronové',
        'sluzba5': 'Testovací zákrok na epilaci',
        'sluzba6': 'Horní ret',
        'sluzba7': 'Brada',
        'sluzba8': 'Brada + krk',
        'sluzba9': 'Kompletní obličej',
        'sluzba10': 'Krk vpředu',
        'sluzba11': 'Paže',
        'sluzba12': 'Předloktí',
        'sluzba13': 'Hřbety rukou + prstů',
        'sluzba14': 'Podpaží (obě)',
        'sluzba15': 'Břicho',
        'sluzba16': 'Záda',
        'sluzba17': 'Ramena',
        'sluzba18': 'Prsa',
        'sluzba19': 'Hrudník',
        'sluzba20': 'Třísla (obě)',
        'sluzba21': 'Intimní partie',
        'sluzba22': 'Třísla + intimní partie',
        'sluzba23': 'Hýždě',
        'sluzba24': 'Stehna (obě)',
        'sluzba25': 'Lýtka (obě)',
        'sluzba26': 'Redukuje pigmentové skvrny a jizvičky po akné',
        'sluzba27': 'Čistí a redukuje rozšířené póry',
        'sluzba28': 'Zmírňuje tvorbu kožního mazu',
        'sluzba29': 'Výsledkem je hladší jemnější svěží pleť',
        'sluzba30': 'Okamžitě viditelný efekt',
        'sluzba31': 'Obličej',
        'sluzba32': 'Obličej + krk',
        'sluzba33': 'Obličej + krk + dekolt',
        'sluzba34': 'Krk',
        'sluzba35': 'Dekolt',
        'sluzba36': 'Hřbet rukou (obě)',
        'sluzba37': 'Odstraňování celulitidy, zpevnění pokožky',
        'sluzba38': 'Formování postavy a zeštíhlení',
        'sluzba39': 'Zlepšení lymfatického toku a mikrocirkulace',
        'sluzba40': 'Zesílení okysličovaní tkání, jejímž výsledkem je zlepšení tonusu kůže a jejich přilehlých tkaní',
        'sluzba41': 'Snížení hloubky vrásek - 43%',
        'sluzba42': 'Zvýšení hustoty pokožky + 53%',
        'sluzba43': 'Snížení nežádoucího objemu podkožního tuku ve spodní třetině obličeje - 48%',
        'sluzba44': 'Výroba kyseliny hyaluronové + 80%',
        'sluzba45': 'Tvorba nového kolagenu + 46%',
        'sluzba46': 'Vhodné pro muže a ženy',
        'cosmprice': 'Od 850 CZK',
        'cosmprice1': 'Diodový laser (cena za 1 aplikaci)',
        'cosmprice2': 'Od 390 CZK',
        'cosmprice3': 'Zdarma',
        'cosmprice4': 'Od 399 CZK',
        'cosmprice5': '1.200 CZK / 10 ošetřeni 10.000 CZK',
        'cosmprice6': '950 CZK / 10 ošetření 8.500 CZK',
        'coloring': 'Services of the Zone of Hairdressers',
        'aboutcolor': 'We work with professional dyes by the company WELLA PROFESSIONAL because there are no half measures for us in this matter - only quality, only WELLA. In the PODIUM color laboratory, you can find over a hundred shades of the long-lasting color KOLESTON PERFECT ME +, and ammonia-free toning dyes COLOR TOUCH. Many of us know how difficult it is to achieve the desired hair color, especially blonde women. That is why our blonde clients highly appreciate the super-shining line of ILLUMINA dyes. And for perfect highlighting, the specialists use the new BLONDORPLEX, which contains the so-called plex technology to protect your hair during the hair coloring process.',
        'strih': 'Dámský střih',
        'strih1': 'Panský střih',
        'strih2': 'Panský střih + úprava vousů',
        'strih3': 'Foukaná',
        'strih4': 'Jednotónové barvení nebo tónování',
        'strih5': 'Komplexní barvení',
        'strih6': 'Procedura ozdravení vlasů WellaPlex',
        'strih7': 'Laminování vlasů s produkty Sebastian Cellophanes',
        'dur': '60 min',
        'dur1': '60 min',
        'dur2': '60 min',
        'dur3': '60 min',
        'dur4': '1,5-2 h',
        'dur5': '3-4 h',
        'dur6': '4-5 h',
        'dur7': '90 min',
        'dur8': '1,5-2 h',
        'desc1': 'Služba zahrnuje podrobnou konzultaci se specialistou, přípravu vlasů před stříháním, základní péči podle typu vlasů, stříhání a účes.',
        'desc2': 'Služba zahrnuje podrobnou konzultaci se specialistou, přípravu a mytí vlasů, stříhání, opakované mytí hlavy, foukání vlasů s přípravky pro styling vlasů nebo bez (v závislosti na typu vlasů).',
        'desc3': 'Služba zahrnuje podrobnou konzultaci se specialistou, přípravu a mytí vlasů, stříhání, úpravu vousů, opakované mytí hlavy, foukání vlasů s přípravky pro styling vlasů nebo bez (v závislosti na typu vlasů).',
        'desc4': 'Služba zahrnuje podrobnou konzultaci se specialistou, přípravu vlasů před účesem, základní péči podle typu vlasů, úpravu vlasů kartáčem nebo stylery (kulma, žehlička).',
        'desc5': 'Proces získání rovnoměrné barvy vlasů. Provádí se různými technikami s využitím jednoho odstínu nebo dvou pro plynulý přechod barev. V laboratoři barev PODIUM naleznete přes sto barevných odstínů odolné barvy KOLESTON PERFECT ME+, tónovací barvy COLOR TOUCH bez amoniaku a moderních zářivých barviv ILLUMINA COLOR.',
        'desc6': 'Typ barvení se zesvětlováním, úplnou nebo částečnou změnou barvy. Můžete si vybrat moderní techniky barvení, jako jsou: shatush, balayage, highlights. Pro ideální zesvětlení používáme nový BLONDORPLEX, který obsahuje plex technologii na ochranu vlasů během barvení.',
        'desc7': 'Populární technika barvení, díky které Vaše vlasy získají jemný přechod barev. Jemné barvení, které nevyžaduje častou úpravu (4-6 měsíců). Tato technika barvení je vhodná absolutně pro všechny, jak pro světlovlásky, tak i tmavovlásky.',
        'desc8': 'Ošetření sérem a maskou WellaPlex. Jejich složení na molekulární úrovni proniká hluboko do vlasů a obnovuje keratinové vazby. Služba zahrnuje konzultaci, mytí hlavy, nanesení séra WellaPlex N.1 elixírové ochrany, nanesení masky WellaPlex N. 2 elixírového stabilizátoru a klasický účes.',
        'desc9': 'Sebastian Cellophanes je speciální technologie, která umožňuje efektivní péči o vlasy barvené, bez života, suché a matné. Prostředek napomáhá kvalitní bílkovinové obnově vlasů a má hluboký kondicionační účinek. Přípravek obsahuje rostlinné bílkoviny a biologicky aktivní látky. Můžete si vybrat čisté složení bez barvy, stejně jako složení s lehkým odstínem.',
        'metro': 'Metro I.P.Pavlova',
        'hour': 'PON-NE 10.00-20.00',
        'service': 'Služby',



    },
    'ru': {
        'about': 'О нас',
        'services': 'Наши услуги',
        'contact': 'Контакты',
        'reserve': 'Забронировать',
        'about1': 'Международная команда специалистов по красоте Podium | Wella Salon предоставляет полный спектр услуг, связанных с индустрией моды и внешнего здоровья. Профессионализм экспертов Podium|Wella Salon позволяет нашей команде динамично развиваться в этой области и отслеживать новые технологии и продукты индустрии. В Podium | Wella Salon существует несколько направлений, поэтому в концепции салона заложена возможность зонирования на специальные, оснащенные по новейшим технологиям залы. Эта возможность создает мастерам условия для полного погружения в работу с клиентом, обеспечивая комфортные условия в общении.',
        'about2': 'Парикмахерский зал - место, где рождается мода. Здесь мы анализируем Вашу внешность, меняем имидж, подчеркиваем естественную красоту - у нас это происходит легко и приятно. Без «навязывания» тенденций, ведь главный успех мастера заключается в том, чтобы клиент остался в гармонии с новым имиджем.',
        'about3': 'Зал визажистов наполнен новыми образами и слово «совершенство» здесь обретает новое значение. При свете софитов и вспышек фотокамер Вы будете безупречны. Совершенно неважно, какие Ваши планы на вечер: возможно Вы примеряете образ скромности «nude» или Вас ждут амбициозные планы сексуального и страстного образа «smokey eyes» - макияж на Вашем лице идеально сохранится до самого утра.',
        'about4': 'Техническое оборудование Зала эстетической медицины не позволит проводить некорректные процедуры «из прошлого века», а напротив - сохранит здоровье и безопасность Вашей кожи, используя современные технологии. Позволит снять накопившиеся стрессы с лица, остановит время и подарит дополнительные часы релакса и умиротворения в Вашей жизни.',
        'about5': 'В зале мастеров маникюра креативные работы и идеальные ногти давно стали новой реальностью и частью нашей жизни. В самой красивой части салона PODIUM Вас ожидает настоящий художник, и, Ваши руки - его холст.',
        'offerText': 'Наши услуги',
        'butn1': 'Подробнее',
        'color': 'Парикмахерский зал',
        'manicure': 'Маникюрный зал',
        'makeup': 'Зал визажистов',
        'cosmetics': 'Зал косметолога',
        'quote': 'Вы платите только, если остались довольны услугой!',
        'follow': 'Подписывайтесь на наш Инстаграм',
        'nailbar': 'Маникюрный зал',
        'nailabout': 'Деликатность и аккуратность — основные принципы нашей работы. Мы с особым вниманием и трепетом относимся к внешнему виду Ваших рук и делаем все возможное для Вашего комфорта. Дизайн - это самый любимый процесс работы. И здесь мы придерживаемся индивидуального подхода, так как все разные и предпочтения в дизайне маникюра у всех индивидуальные. Для нас не существует границ, поэтому даже самые смелые идеи будут отражены в дизайне маникюра. Мы с радостью воплотим все Ваши пожелания.',
        'nail': 'Мужской маникюр',
        'nail1': 'Маникюр без покрытия',
        'nail2': 'Маникюр с покрытием',
        'nail3': 'Французский маникюр',
        'nail4': 'Маникюр + укрепление ногтей',
        'nail5': 'Маникюр + коррекция гелевого наращивания',
        'nail6': 'Маникюр + гелевое наращивание',
        'min': '30 мин',
        'min1': '40 min',
        'min2': '90 мин',
        'min3': '90 мин',
        'min4': '90 мин',
        'min5': '90 мин',
        'min6': '120 мин',
        'visage': 'Услуги зала визажистов',
        'visageabout': 'Макияж - это образ жизни, это осознанный выбор женщины, ровно такой же как выбирать себе стиль одежды на каждый день. Именно поэтому сегодня макияж стал направлением, одним из видов настоящего современного искусства. Он помогает подчеркнуть естественную красоту, а при желании полностью изменить привычный образ. Изысканный и сдержанный макияж в нежных оттенках, дерзкий дымчатый смоки с мерцающими блестками или классика жанра — яркие губы и стрелки? Мы с удовольствием обсудим и осуществим Ваши любые, даже самые смелые идеи. Также в зоне визажистов Вы можете воспользоваться услугами по созданию идеальной формы бровей, ведь аккуратные и ухоженные брови - это одна из составляющих частей безупречного образа.',
        'brow': 'Ламинирование + коррекция бровей',
        'brow1': 'Окрашивание краской или хной + коррекция бровей',
        'brow2': 'Ламинирование + окрашивание + коррекция бровей',
        'brow3': 'Дневной макияж',
        'brow4': 'Вечерний макияж',
        'brow5': 'Свадебный макияж',
        'browtime': '40 мин',
        'browtime1': '40 мин',
        'browtime2': '60 мин',
        'browtime3': '40 мин',
        'browtime4': '60 мин',
        'browtime5': '90 мин',
        'browtext': 'Ламинирование волосков специальными составами бренда THUYA PROFESSIONAL . Ламинирование делает волоски более послушными и добавляет им визуальный объём. Эффект такой долговременной укладки держится от 4 до 6 недель. Коррекция бровей - это придание желаемой формы с помощью воска ITALWAX и пинцета для детальной коррекции.',
        'browtext1': 'При окрашивании мы используем краску бренда THUYA PROFESSIONAL для придания максимально натурального цвета бровей и легкой тени на коже. Благодаря кератину и аргановому маслу в составе хорошо питает и ухаживает за волосками. Для окрашивания хной используется продукт популярного бренда BROWXENNA. Такое окрашивание подходит для любительниц четких контуров и графичных бровей. Коррекция бровей - это придание желаемой формы с помощью воска ITALWAX и пинцета для детальной коррекции.',
        'browtext2': 'В услугу входит ламинирование волосков специальными составами бренда THUYA PROFESSIONAL, окрашивание бровей на выбор краской THUYA PROFESSIONAL или хной BROWXENNA, коррекция бровей - это придание желаемой формы с помощью воска ITALWAX и пинцета для детальной коррекции.',
        'browtext3': 'Повседневный визаж представлен в неброских тонах, которые подчеркивает вашу естественность и скрывает недостатки, придавая Вашему образу привлекательный и ухоженный вид.',
        'browtext4': 'Это более яркий макияж, чаще всего выбранный для вечеринки или праздника. Образ может быть дерзким, или наоборот - нежным. Наши визажисты подберут косметику, учитывая все особенности вашей кожи, чтобы в течении всего вечера макияж оставался идеальным.',
        'browtext5': 'Мы с радостью поможем Вам создать идеальный свадебный макияж, ведь этот день должен быть незабываемым, а Вы - самой красивой. Свадебный макияж должен оставаться безупречным на протяжении всего дня, подчеркивая свежесть лица утром и придавая великолепное сияние коже вечером.',
        'cosmetic': 'Услуги косметологического зала',
        'kosmetika': 'Косметика',
        'kosmetika1': 'Лазерная эпиляция',
        'kosmetika2': 'Алмазная микродермабразия',
        'kosmetika3': 'Фотоомоложение',
        'kosmetika4': 'LPG липомассаж',
        'kosmetika5': 'LPG Lift массаж лица',
        'sluzba': 'Чистка лица ультразвуком',
        'sluzba1': 'Чистка лица-восстановление для проблематической кожи',
        'sluzba2': 'Профессиональные кислотные пилинги',
        'sluzba3': 'Восстанавливающий уход',
        'sluzba4': 'Увлажняющий уход с высокой концентрацией гиалуроновой кислоты',
        'sluzba5': 'Тестирование эпиляции',
        'sluzba6': 'Верхняя губа',
        'sluzba7': 'Подбородок',
        'sluzba8': 'Подбородок + шея',
        'sluzba9': 'Лицо полностью',
        'sluzba10': 'Передняя часть шеи',
        'sluzba11': 'Руки полностью',
        'sluzba12': 'Руки до локтя',
        'sluzba13': 'Пальцы',
        'sluzba14': 'Подмышки (обе)',
        'sluzba15': 'Дорожка на животе',
        'sluzba16': 'Спина',
        'sluzba17': 'Плечи',
        'sluzba18': 'Грудь (вокруг сосков)',
        'sluzba19': 'Грудь полностью',
        'sluzba20': 'Линии бикини',
        'sluzba21': 'Интимные партии',
        'sluzba22': 'Линии бикини + интимные партии',
        'sluzba23': 'Ягодицы',
        'sluzba24': 'Бедра',
        'sluzba25': 'Голени',
        'sluzba26': 'Уменьшает пигментные пятна и шрамы от акне',
        'sluzba27': 'Очищает и уменьшает расширенные поры',
        'sluzba28': 'Уменьшает выработку кожного жира',
        'sluzba29': 'Выравнивает тон лица',
        'sluzba30': 'Результат - гладкая, свежая кожа',
        'sluzba31': 'Лицо',
        'sluzba32': 'Лицо + шея',
        'sluzba33': 'Лицо + шея + декольте',
        'sluzba34': 'Шея',
        'sluzba35': 'Декольте',
        'sluzba36': 'Тыльная сторона руки + пальцы',
        'sluzba37': 'Устранение целлюлита',
        'sluzba38': 'Уменьшение объемов тела, моделирование фигуры',
        'sluzba39': 'Подтяжка кожи, общее укрепление и оздоровление организма',
        'sluzba40': 'Улучшение микроциркуляции крови',
        'sluzba41': 'Уменьшение глубины морщин - 43%',
        'sluzba42': 'Увеличение «плотности» кожи + 53%',
        'sluzba43': 'Уменьшение нежелательного объема подкожного жира в нижней трети лица - 48%',
        'sluzba44': 'Выработка гиалуроновой кислоты + 80%',
        'sluzba45': 'Образованиe нового коллагена + 46%',
        'sluzba46': 'Подходит для мужчин и для женщин',
        'cosmprice': 'от 850 CZK',
        'cosmprice1': 'Диодный лазер (цена за 1 процедуру)',
        'cosmprice2': 'От 390 CZK',
        'cosmprice3': 'Бесплатно',
        'cosmprice4': 'От 399 CZK',
        'cosmprice5': '1200 CZK / 10 процедур 10 000 CZK',
        'cosmprice6': '950 CZK / 10 процедур 8.500 CZK',
        'coloring': 'Услуги парикмахерского зала',
        'aboutcolor': 'Мы работаем с профессиональными красителями компании WELLA PROFESSIONAL, потому что в этом вопросе для нас не существует полумер - только качество, только WELLA. В колор-лаборатории PODIUM можно найти свыше ста цветовых оттенков стойкого красителя KOLESTON PERFECT ME+, безаммиачные тонирующие красители COLOR TOUCH. Многие знают насколько сложно добиться правильного, того самого заветного цвета волос, особенно у женщин - блондинок. Именно поэтому наши клиентки-блондинки высоко ценят супер-сияющую линию красителей ILLUMINA. А для идеального осветления мастера используют новый BLONDORPLEX, который содержит в себе plex-технологию для защиты от разрушения во время окрашивания.',
        'strih': 'Женская стрижка',
        'strih1': 'Мужская стрижка',
        'strih2': 'Мужская стрижка + коррекция бороды',
        'strih3': 'Укладка',
        'strih4': 'Однотонное окрашивание или тонирование',
        'strih5': 'Сложное окрашивание',
        'strih6': 'Процедура оздоровления волос WellaPlex',
        'strih7': 'Уходовое ламинирование Sebastian Cellophanes',
        'dur': '60 мин',
        'dur1': '60 мин',
        'dur2': '60 мин',
        'dur3': '60 мин',
        'dur4': '1,5-2 часа',
        'dur5': '3-4 часа',
        'dur6': '4-5 часа',
        'dur7': '90 мин',
        'dur8': '1,5-2 часа',
        'desc1': 'В услугу входит подробная консультация с мастером, подготовка волос перед стрижкой, базовый уход по типу волос, стрижка и повседневная укладка.',
        'desc2': 'В услугу входит подробная консультация с мастером, подготовка волос в мойке, стрижка, повторное мытьё головы, сушка с или без использованием средств для укладки (в зависимости от типа волос).',
        'desc3': 'В услугу входит подробная консультация с мастером, подготовка волос в мойке, стрижка, коррекция бороды, повторное мытьё головы, сушка с или без использованием средств для укладки (в зависимости от типа волос).',
        'desc4': 'В услугу входит подробная консультация с мастером подготовка волос перед укладкой, базовый уход по типу волос, укладка на брашинг или стайлер (плойка, утюжок).',
        'desc5': 'Процесс создания равномерного цвета на волосах. Выполняется в различных техниках с использованием одного оттенка или двух для плавного перехода цвета. В колор-лаборатории PODIUM можно найти более ста цветовых оттенков стойкого красителя KOLESTON PERFECT ME+, безаммиачные тонирующие красители COLOR TOUCH и ультрасовременный сияющий краситель ILLUMINA COLOR.',
        'desc6': 'Вид окрашивания с осветлением, полной или частичной сменой цвета. Возможность выбора современных техник окрашивания, таких как : Shatush, Balayage, Highlights. Для идеального осветления мы используем новый BLONDORPLEX, который содержит в себе plex-технологию для защиты от разрушения во время окрашивания.',
        'desc7': 'Популярная техника окрашивания, благодаря которой создаётся мягкий перелив цвета. Щадящее окрашивание, не требующее частой коррекции (4-6 месяцев). Данное окрашивание подходит абсолютно всем, как обладательницам светлых волос, так и темных.',
        'desc8': 'Процедура с использованием сыворотки и маски WellaPlex. Их состав на молекулярном уровне проникает вглубь волоса и восстанавливает кератиновые связи. В услугу входит консультация, мытьё головы, нанесение сыворотки wellaplex N. 1 элексир-защита , нанесение маски wellaplex N. 2 элексир-стабилизатор, повседневная укладка.',
        'desc9': 'Sebastian Cellophanes – особая технология, позволяющая эффективно ухаживать за окрашенными, безжизненными, сухими и тусклыми волосами. Средство способствует качественному белковому восстановлению волос и имеет глубокое кондиционирующее действие. В формулу препарата входят растительные протеины и биологически активные вещества. Возможность выбора чистого состава без цвета, так и состава с легким оттенком.',
        'metro': 'Метро I.P.Pavlova',
        'hour': 'ПН-ВС 10.00-20.00',
        'service': 'Услуги',




    },
    'en': {
        'about': 'About us',
        'services': 'Our services',
        'service': 'Services',
        'contact': 'Contacts',
        'reserve': 'Reserve',
        'about1': 'The international team of beauty specialists of Podium | Wella Salon provides a full range of services related to fashion industry and external health. The professionalism of Podium|Wella Salon experts allows our team to dynamically develop in this area and follow new technologies and products in this industry. There are several approaches in Podium | Wella Salon, thus the concept of the salon is based on the possibility to be divided into special zones equipped with the latest technologies. This option creates conditions for our specialists to fully immerse in the work with the client, also providing comfortable conditions in communication.',
        'about2': 'The Zone of Hairdressers is the place where fashion is born. Here we analyze your appearance, change your image, and enhance your natural beauty. You will feel relaxed and comfortable with us. We do not impose trends on you because the main success of the specialist is to make the client in happy and comfortable with the new image.',
        'about3': 'The Zone of Makeup Artists is full of new styles and the word perfection takes on a new meaning here. You will be flawless in the world of spotlights and camera flashes. It does not matter what your plans are for the evening. Perhaps you will choose a modest nude look or you have ambitious plans and opt for a sexy and hot look of smoky eyes. Either way the makeup on your face will last until morning.',
        'about4': 'Technical equipment in the Zone of Aesthetic Medicine will not allow performing incorrect procedures from the last century, but it will protect the health and safety of your skin, using modern technologies. It will allow you to remove accumulated stress from your face, stop time and gain additional hours of relaxation and peace in your life.',
        'about5': 'In the Zone of Manicure Specialists, creative work and perfect nails have long become a new reality and part of our lives. In the most beautiful part of the PODIUM salon, the real artist awaits you and your hands will be their canvas.',
        'offerText': 'Our services ',
        'butn1': 'Prices',
        'color': 'Hairdressers Hall',
        'manicure': 'Manicure Hall',
        'makeup': 'Make-up Artist Hall',
        'cosmetics': 'Aesthetic Medicine Hall',
        'quote': 'Pay only if you are satisfied!',
        'follow': 'Follow us on Instagram',
        'nailbar': 'Manicure Hall',
        'nailabout': 'Sensitivity and accuracy are the basic principles of our work. We pay special attention to the appearance of your hands and do everything possible for your comfort. Nail design is our most favorite part of the process. We take an individual approach even in this case because everyone is different and the preferences in manicure design are individual everyone. There are no limits for us because even the most daring ideas will be reflected in the manicure design. We are happy to fulfill all your wishes.',
        'nail': 'Male Manicure',
        'nail1': 'Manicure Without Gel Polish',
        'nail2': 'Manicure + Gel Polish',
        'nail3': 'French Manicure',
        'nail4': 'Manicure + Nail Strengthening',
        'nail5': 'Manicure + Correction of Gel Extensions',
        'nail6': 'Manicure + Gel Extensions',
        'min': '30 min',
        'min1': '40 min',
        'min2': '90 min',
        'min3': '90 min',
        'min4': '90 min',
        'min5': '90 min',
        'min6': '120 min',
        'visage': 'Services of the Zone of Makeup Artists',
        'visageabout': 'Makeup is a lifestyle and a conscious choice of a woman just as choosing a style for everyday clothing. That is why nowadays makeup has become a movement, one of the types of contemporary art. It helps to enhance natural beauty and completely change the everyday look. Do you want a classy and discreet makeup in light shades, bold smoky makeup with glitters, or the classic bold lip and eyeliner? We are happy to discuss and implement any ideas, even the most daring ones. In the Zone of Makeup Artists, you can also use services to create the perfect shape of your eyebrows because neat and well-groomed eyebrows are one of the aspects of a flawless look.',
        'brow': 'Brow Lamination + Correction',
        'brow1': 'Brow Tinting or Henna Brow Tinting + Correction',
        'brow2': 'Lamination + Coloring + Correction',
        'brow3': 'Daytime Makeup',
        'brow4': 'Evening Makeup',
        'brow5': 'Wedding Makeup',
        'browtime': '40 min',
        'browtime1': '40 min',
        'browtime2': '60 min',
        'browtime3': '40 min',
        'browtime4': '60 min',
        'browtime5': '90 min',
        'browtext': 'Lamination of eyebrows uses special blends by the brand THUYA PROFESSIONAL. The lamination makes the eyebrows more manageable and adds a visual volume to them. The effect of such long-term styling lasts from 4 to 6 weeks. Eyebrow correction is shaping the eyebrows to the desired shape using ITALWAX wax and tweezers for precision.',
        'browtext1': 'During coloring we use the brand THUYA PROFESSIONAL hair dye to get a maximally natural color to the eyebrows and light shade to the skin. Thanks to keratin and argan oil in the composition, it nourishes and cares for the hair very well. A product of the popular brand BROWXENNA is used for henna coloring. This way of coloring is suitable for the lovers of defined contours and graphic eyebrows.Eyebrow correction is shaping the eyebrows to the desired shape using ITALWAX wax and tweezers for precision.',
        'browtext2': 'The service includes lamination of eyebrows, using special blends by the brand THUYA PROFESSIONAL, and eyebrow coloring, using THUYA PROFESSIONAL hair dye or BROWXENNA henna. Eyebrow correction is shaping the eyebrows to the desired shape using ITALWAX wax and tweezers for precision.',
        'browtext3': 'Everyday makeup is presented in subtle tones that enhance your natural beauty and hide any flaws, giving you an attractive and neat look.',
        'browtext4': 'This is a bolder makeup, mostly chosen for a party or festive event. Your look can be bold or light. Our makeup artists will choose the cosmetics based on all the features of your skin to make your makeup perfect throughout the entire evening.',
        'browtext5': 'We are happy to help you create the perfect wedding makeup because this day should be unforgettable and you the most beautiful. Wedding makeup must remain flawless all day long, enhancing the freshness of the face in the morning and giving a magnificent glow to the skin in the evening.',
        'cosmetic': 'Aesthetic Medicine Hall',
        'kosmetika': 'Cosmetic Treatments',
        'kosmetika1': 'Laser Epilation',
        'kosmetika2': 'Diamond Microdermabrasion',
        'kosmetika3': 'IPL Rejuvenation',
        'kosmetika4': 'LPG Lipomassage',
        'kosmetika5': 'LPG lift masáž obličeje',
        'sluzba': 'Ultrasonic Face Cleaning',
        'sluzba1': 'Nourishing Cleaning for Problematic Skin',
        'sluzba2': 'Professional Acid Peels',
        'sluzba3': 'Regeneration Treatment',
        'sluzba4': 'Hydratation Treatment with high concetrate Hyaluronic Acid',
        'sluzba5': 'Epilation testing procedure',
        'sluzba6': 'Upper lip',
        'sluzba7': 'Chin',
        'sluzba8': 'Chin + Neck',
        'sluzba9': 'Complete Face',
        'sluzba10': 'Neck in front (overgrown beard on the neck)',
        'sluzba11': 'Arm',
        'sluzba12': 'Forearm',
        'sluzba13': 'Backs of hands + Fingers',
        'sluzba14': 'Armpit (both)',
        'sluzba15': 'Belly',
        'sluzba16': 'Back',
        'sluzba17': 'Shoulders',
        'sluzba18': 'Breasts (around the areola)',
        'sluzba19': 'Chest',
        'sluzba20': 'Bikini lines',
        'sluzba21': 'Intimate Parts',
        'sluzba22': 'Bikini lines + Intimate parts',
        'sluzba23': 'Buttocks',
        'sluzba24': 'Hips',
        'sluzba25': 'Shins',
        'sluzba26': 'Reduces pigment spots and acne scars',
        'sluzba27': 'Cleans and reduces enlarged pores',
        'sluzba28': 'Reduces the production of skin fat',
        'sluzba29': 'The result is smoother softer fresh skin',
        'sluzba30': 'Immediate visible effect',
        'sluzba31': 'Face',
        'sluzba32': 'Face + Neck',
        'sluzba33': 'Face + Neck + Décolétte',
        'sluzba34': 'Neck',
        'sluzba35': 'Décolétte',
        'sluzba36': 'Back of hands (both)',
        'sluzba37': 'Removing cellulite',
        'sluzba38': 'Body shaping and slimming',
        'sluzba39': 'Improvement of lymph flow and microcirculation',
        'sluzba40': 'Strengthening of oxidized tissues, the potential result is better tone of the skin and their adjacent tissues',
        'sluzba41': 'Reduction of wrinkle depth - 43%',
        'sluzba42': 'Increase in skin density + 53%',
        'sluzba43': 'Reduction of unwanted volume of subcutaneous fat in the lower third of the face - 48%',
        'sluzba44': 'Production of hyaluronic acid + 80%',
        'sluzba45': 'New collagen formation + 46%',
        'sluzba46': 'Suitable for men and women',
        'cosmprice': 'from 850 CZK',
        'cosmprice1': 'Diode Laser (price for 1 application)',
        'cosmprice2': 'From 390 CZK',
        'cosmprice3': 'Free',
        'cosmprice4': 'From 399 CZK',
        'cosmprice5': '1.200 CZK / 10 treatment 10.000 CZK',
        'cosmprice6': '950 CZK / 10 treatments 8.500 CZK',
        'coloring': 'Services of the Zone of Hairdressers',
        'aboutcolor': 'We work with professional dyes by the company WELLA PROFESSIONAL because there are no half measures for us in this matter - only quality, only WELLA. In the PODIUM color laboratory, you can find over a hundred shades of the long-lasting color KOLESTON PERFECT ME +, and ammonia-free toning dyes COLOR TOUCH. Many of us know how difficult it is to achieve the desired hair color, especially blonde women. That is why our blonde clients highly appreciate the super-shining line of ILLUMINA dyes. And for perfect highlighting, the specialists use the new BLONDORPLEX, which contains the so-called plex technology to protect your hair during the hair coloring process.',
        'strih': 'Female Haircut',
        'strih1': 'Male Haircut',
        'strih2': 'Male Haircut + Beard Grooming',
        'strih3': 'Hair Styling',
        'strih4': 'Single Tone Coloring or Hair Toning',
        'strih5': 'Complex Coloring',
        'strih6': 'Hair Healing Procedure WellaPlex',
        'strih7': 'Hair Lamination Sebastian Cellophanes',
        'dur': '60 min',
        'dur1': '60 min',
        'dur2': '60 min',
        'dur3': '60 min',
        'dur4': '1,5-2 h',
        'dur5': '3-4 h',
        'dur6': '4-5 h',
        'dur7': '90 min',
        'dur8': '1,5-2 h',
        'desc1': 'The service includes detailed consultation with a specialist, hair preparation before cutting, basic care by hair type, haircut and styling.',
        'desc2': 'The service includes detailed consultation with a specialist, hair preparation for washing, haircut, repeated head washing, hair drying with or without the use of styling products (depending on hair type).',
        'desc3': 'The service includes detailed consultation with a specialist, hair preparation for washing, haircut, beard grooming, repeated head washing, hair drying with or without the use of styling products (depending on hair type).',
        'desc4': 'The service includes detailed consultation with a specialist, hair preparation before styling, basic care by hair type, brushing or using styling tools (curling iron, hair straightener).',
        'desc5': 'This is a process of creating a uniform color of the hair, performed by various techniques using one or two shades for a smooth color transition. In the PODIUM color laboratory, you can find over a hundred shades of the long-lasting color KOLESTON PERFECT ME +, ammonia-free toning dyes COLOR TOUCH, and modern shining dyes ILLUMINA COLOR.',
        'desc6': 'This is a type of coloring with highlighting, full or partial color change. You can choose modern coloring techniques such as: Shatush, Balayage, Highlights. For perfect highlighting, we use the new BLONDORPLEX, which contains plex technology to protect your hair during the hair coloring process.',
        'desc7': 'his is a popular coloring technique that creates a smooth transition of your hair color. It is a gentle coloring that does not require frequent styling (4-6 months). This coloring technique is suitable for absolutely anyone, both women with blonde and dark hair.',
        'desc8': 'This procedure uses a serum and WellaPlex hair mask. Their composition at the molecular level penetrates deep into the hair and restores keratin bonds. The service includes consultation, head washing, application of WellaPlex N. 1 serum elixir protection, application of WellaPlex N. 2 mask elixir stabilizer, and hair styling.',
        'desc9': 'Sebastian Cellophanes is a special technology that enables an effective treatment for colored, lifeless, dry, and dull hair. This product promotes high-quality protein hair recovery and has a deep conditioning effect. The formula contains plant proteins and biologically active substances. You can choose a pure composition without color as well as compositions with a light shade.',
        'metro': 'Metro I.P.Pavlova',
        'hour': 'MON-SU 10.00-20.00',





    },



}


$(function() {
    $('.translate').click(function() {
        var lang = $(this).attr('id');
        saveLocalLang(lang)

        $('.lang').each(function(index, item) {
            $(this).text(arrLang[lang][$(this).attr('key')]);
        });
    });
});


function saveLocalLang(language) {
    let langs
    if (localStorage.getItem('langs') === null) {
        langs = []
    } else {
        langs = JSON.parse(localStorage.getItem('langs'))
    }
    langs.push(language)
    localStorage.setItem('langs', JSON.stringify(langs))
}

function getLocalLang() {
    let langs
    if (localStorage.getItem('langs') === null) {
        lang = []
    } else {
        langs = JSON.parse(localStorage.getItem('langs'))
    }
    langs.forEach(function(language) {
        let lang = langs[langs.length - 1]
        setTimeout(() => {

            $('.lang').each(function(index, item) {
                $(this).text(arrLang[lang][$(this).attr('key')])
            });
        }, 0);

    });
}